language: python
python:
  - "3.3"
install:
  - pip install coveralls
script:
  - coverage run --source=lib31 setup.py test2
after_success:
  - coveralls
notifications:
  email:
    - roll@respect31.com