language: python
python:
  - '3.3'
install:
  - pip install coveralls
script:
  - coverage run --source=lib31 setup.py test
after_success:
  - coveralls
notifications:
  email:
    - post@respect31.com
deploy:
  provider: pypi
  user: roll
  password:
    secure: jFRWJAyhP5RA9j8CEpJzwJhwZmbfcxW1HpRO43mMu2/Nh3FW7GdisUovCLOS/khygJvh86vfe6m69+GEVuH/VgUEw8GcdZ41Zcla0ZnBhQrH0PTQel5Fou85foD7yXf42toVY3DV7C/JPk8PK3swSlIJ26n4dVreI7y1xvRmVHk=