#DO NOT CHANGE THIS FILE. SOURCE IS IN "_sources" DIRECTORY.

language: 
  python

python:
  - '3.3'
  - '3.4'

install:
  - pip install coveralls
  - pip install nose jinja2

script:
  - coverage run --source=box setup.py test

after_success:
  - coveralls

notifications:
  email:
    - roll@respect31.com

deploy:
  provider: pypi
  user: roll
  password:
    secure: jFRWJAyhP5RA9j8CEpJzwJhwZmbfcxW1HpRO43mMu2/Nh3FW7GdisUovCLOS/khygJvh86vfe6m69+GEVuH/VgUEw8GcdZ41Zcla0ZnBhQrH0PTQel5Fou85foD7yXf42toVY3DV7C/JPk8PK3swSlIJ26n4dVreI7y1xvRmVHk=
  on:
    tags: true
    all_branches: true