#Builded for {{ name }} {{ version }} from _templates/.travis.yml

language: python
python:
  - '3.3'
install:
  - pip install coveralls
script:
  - coverage run --source={{ name }} setup.py test
after_success:
  - coveralls
notifications:
  email:
    - post@respect31.com
deploy:
  provider: pypi
  user: {{ pypi_user }}
  password:
    secure: {{ pypi_password_secure }}